image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup utilities
    before:
      sudo apt-get update -y;
      sudo apt-get install -y tree jq unzip curl git;

  - name: AWS CLI
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before:
      cd /workspace;
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip";
      unzip awscliv2.zip;
      sudo ./aws/install;
      cd $THEIA_WORKSPACE_ROOT
