#!/usr/bin/bash

echo "== Create a bucket"
if [ -z "$1" ]; then
    echo "The fisrt agurment needs to be a BUCKET_NAME here"
    exit 1
fi

if [ -z "$2" ]; then
    echo "The second agurment needs to be a REGION_NAME here ex: ap-northeast-1"
    exit 2
fi

if [ -z "$3" ]; then
    echo "The third agurment needs to be a LOCALTION_NAME name here ex: ap-northeast-1"
    exit3
fi

BUCKET_NAME=$1
REGION_NAME=$2
LOCALTION_NAME=$3

#https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
aws s3api create-bucket \
--bucket $BUCKET_NAME \
--region=$REGION_NAME \
--create-bucket-configuration LocationConstraint=$LOCALTION_NAME \
--query Location \
--output text
