#!/usr/bin/bash

if [ -z "$1" ]; then
    echo "The fisrt agurment needs to be a bucket name"
    exit 1
fi

if [ -z "$2" ]; then
    echo "The second agurment needs to be a region name ex: ap-northeast-1"
fi

BUCKET_NAME=$1
REGION_NAME=$2
LOCALTION_NAME=$3

#https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
aws s3api create-bucket \
--bucket $BUCKET_NAME \
--region=$REGION_NAME \
--create-bucket-configuration LocationConstraint=$LOCALTION_NAME

