#!/usr/bin/bash
echo "==  delete-objects"


# validate bucket name 
if [ -z "$1" ]; then
    echo "The fisrt agurment must give a bucket name!"
    exit 1
fi

# check filename prefix bucket name 
# if [ -z "$2" ]; then
#     echo "The fisrt agurment must give a fileName eg. ./bucket my-bucket-name filename"
#     exit 2
# fi

BUCKET_NAME=$1
FILENAME=$2

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/ojebcts_delete.json

aws s3api delete-objects --bucket $BUCKET_NAME --delete  file:///tmp/ojebcts_delete.json