#!/usr/bin/bash
echo "== List newest buckets by create date"

# aws s3api list-buckets --query 'Buckets[].Name' --output text
aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[0] | .Name'

