#!/usr/bin/bash
echo "==  put_object"


# validate bucket name 
if [ -z "$1" ]; then
    echo "The fisrt agurment must give a bucket name!"
    exit 1
fi

# check filename prefix bucket name 
if [ -z "$2" ]; then
    echo "The fisrt agurment must give a fileName eg. ./bucket my-bucket-name filename"
    exit 2
fi

BUCKET_NAME=$1
FILENAME=$2
OBJECT_KEY=$(basename "$FILENAME")
echo $OBJECT_KEY
aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key  $OBJECT_KEY