AWSTemplateFormatVersion: 2010-09-09
Description: A simple s3 bucket
Resources:
  S3Bucket:
    #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-s3.html
    Type: 'AWS::S3::Bucket'
    # Properties:
    # We don't need to suplly a bucket name as AWS will gererate a randmon bucket name for us.
